"""Write build/README.md: one section per sheet (purpose, inputs, sources, convention, status, audit) plus the
list of printed course values that disagree with an independent computation.

Everything is taken from the sheet modules' HeaderBlock and SheetDoc, so the README cannot drift from the sheets.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from bbtools.constant_definitions import differences
from bbtools.constants import ROOT, TABLE_SOURCES, load_all
from bbtools.xlsx_style import HeaderBlock

README = ROOT / "build" / "README.md"


@dataclass(frozen=True)
class SheetDoc:
    """What the README says about one sheet, beyond its header block."""

    sheet: str
    purpose: str
    inputs: str
    audit: str                        # stats-auditor result, or why none was needed
    disagreements: tuple[str, ...]    # printed course values that disagree with the computation


def _sheet_section(header: HeaderBlock, doc: SheetDoc) -> list[str]:
    """Markdown for one sheet."""
    lines = [
        f"## {doc.sheet}: {header.tool}", "",
        f"- **Purpose:** {doc.purpose}",
        f"- **Inputs:** {doc.inputs}",
        f"- **Course source:** {header.source}",
        f"- **Convention:** {header.convention}",
        f"- **Status:** {header.status.value}: {header.status_detail}",
        f"- **Audit:** {doc.audit}",
    ]
    if doc.disagreements:
        lines += ["- **Printed course values that disagree with the computation** (kept as printed in the oracle; "
                  "tested as strict expected failures):"]
        lines += [f"  - {item}" for item in doc.disagreements]
    return lines + [""]


def _constants_section() -> list[str]:
    """Markdown table of printed constants more than one unit of their last digit from their definition."""
    names = {s.key: f"{s.key} ({s.origin})" for s in TABLE_SOURCES}
    larger = [d for d in differences(load_all()) if not d.rounding_only]
    lines = [
        "## Constants that differ from their mathematical definition", "",
        "Each printed constant was compared with its definition (tests/test_constant_definitions.py). "
        "Differences of at most one unit in the last printed digit (rounding of rounded inputs) are not listed. "
        "The calculators still use the printed values (convention decision 4); nothing was overwritten.", "",
        "| Table | Constant | n | Printed | Definition | Off by (units of last digit) |",
        "|---|---|---|---|---|---|",
    ]
    lines += [f"| {d.table} | {d.symbol} | {d.n} | {d.printed} | {d.definition:.5f} | {d.units:g} |" for d in larger]
    lines += ["", "Tables: " + "; ".join(names.values()) + ".", ""]
    return lines


def write_readme(sheets: list[tuple[HeaderBlock, SheetDoc]], path: Path = README) -> Path:
    """Write the README for the given sheets, in workbook order."""
    lines = [
        "# bb_toolkit.xlsx", "",
        "Offline calculators for the Black Belt exam. Generated by `src/bbtools/` "
        "(`PYTHONPATH=src python3 -m bbtools.build_workbook`); never edit by hand.", "",
        "**Use:** type into the yellow cells only; green cells are results. A result row stays empty until the inputs "
        "it needs are filled. Every sheet starts with its course source, convention and verification status. "
        "Excel recalculates the whole file when it opens.", "",
    ]
    for header, doc in sheets:
        lines += _sheet_section(header, doc)
    lines += _constants_section()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    return path
